import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

@Component({
  templateUrl: 'home.html'
})
export class HomePage {
  ecal;

  constructor(public navCtrl: NavController) {}

  initializeItems() {
    this.ecal = [
      {acronyme: "2dF", words: "Two Degree Field"},
      {acronyme: "2MASS", words: "Two Micron All Sky Survey"},
      {acronyme: "4MOST", words: "4-meter Multi Object Spectroscopic Telescope (Instrument for the ESO VISTA telescope, 2019)"},
      {acronyme: "A&A", words: "Astronomy and Astrophysics (Journal) / Authentification and Authorisation"},
      {acronyme: "ABCL", words: "As Build Configuration List"},
      {acronyme: "AC", words: "Alternating Current"},
      {acronyme: "ACRD", words: "Additional Cosmology Requirements Document"},
      {acronyme: "ACS", words: "Advanced Camera for Survey (HST camera)"},
      {acronyme: "AD", words: "Applicable Document"},
      {acronyme: "ADASS", words: "Astronomical Data Analysis Software and System"},
      {acronyme: "ADC", words: "Analog to Digital Converter"},
      {acronyme: "ADD", words: "Architectural Design Review"},
      {acronyme: "ADS", words: "Airbus Defence and Space"},
      {acronyme: "ADU", words: "Analog to Digital Unit"},
      {acronyme: "AEGIS", words: "All-wavelength Extended Groth strip International Survey"},
      {acronyme: "AGB", words: "Asymptotic Giant Branch"},
      {acronyme: "AGES", words: "AGN and Galaxy Evolution Survey"},
      {acronyme: "AGN", words: "Active Galactic Nucleus/Nuclei"},
      {acronyme: "AIfA", words: "Argelander-Institut für Astronomie (Bonn Germany)"},
      {acronyme: "AIM", words: "Action Items Manager / Astrophysique Instrumentation Modelisation (CEA-CNRS, Saclay, France)"},
      {acronyme: "Airbus DS", words: "Airbus Defence and Space (Ex-Astrium)"},
      {acronyme: "AIT", words: "Assembly Integration and Testing / Assembly Integration and Test"},
      {acronyme: "AIV", words: "Assembly Integration and Verification"},
      {acronyme: "ALMA", words: "Atacama Large Millimetre/Submillimetre Array (International observatory in Charnator, Chili)"},
      {acronyme: "AMR", words: "Adaptive Mesh Refinement"},
      {acronyme: "ANNz", words: "Artificial Neural Network for photo-z measurement (photometric redshift measurement method)"},
      {acronyme: "AO", words: "Announcement of Opportunity"},
      {acronyme: "AOCS", words: "Attitude and Orbit Control System"},
      {acronyme: "APE", words: "Absolute Pointing Error"},
      {acronyme: "API", words: "Application Programming Interface"},
      {acronyme: "AR", words: "Acceptance Review (instruments) / Anti-Reflection"},
      {acronyme: "APC", words: "laboratoire AstroParticule et Cosmologie (Paris, France)"},
      {acronyme: "APID", words: "Application Process ID"},
      {acronyme: "ASFT", words: "AStrium France Toulouse (Currently Airbus Defence and Space Toulouse)"},
      {acronyme: "ASI", words: "Agenzia Spaziale Italiana (Italy)"},
      {acronyme: "ASIC", words: "Application Specific Integrated Circuit"},
      {acronyme: "AST", words: "EADS ASTrium (Currently Airbus Defence and Space, Airbus DS)"},
      {acronyme: "ASW", words: "Application SoftWare"},
      {acronyme: "ATB", words: "Agency Technology Transfer Board"},
      {acronyme: "ATC", words: "Astronomy Technology Centre (Edinburgh, UK)"},
      {acronyme: "ATHENA", words: "Advanced Telescope for High Energy Astrophysics"},
      {acronyme: "AVM", words: "AVionic Model"},
      {acronyme: "AWG", words: "(ESA) Astronomy Working Group"},
      {acronyme: "aXe", words: "Software package for extraction of spectra from HST grism observations"},
      {acronyme: "B-mode", words: "Non-lensing signal in gravitational shear analysis - Curl term 'B' from analogy with Electromagnetic signal"},
      {acronyme: "BAO", words: "Baryonic Acoustic Oscillations"},
      {acronyme: "BASSICC", words: "BAO SimulationS at the Institute for Computational Cosmology"},
      {acronyme: "BBM", words: "Bread Board Model"},
      {acronyme: "BBN", words: "Big Bang Nucleosynthesis"},
      {acronyme: "BC", words: "Bus Control"},
      {acronyme: "BCN", words: "Barcelona (consortium of institution in Barcelona for the FWA)"},
      {acronyme: "BELSPO", words: "BELgian Science Policy Office (Belgium)"},
      {acronyme: "BOL", words: "Beginning Of Life"},
      {acronyme: "BOSS", words: "Baryon Oscillation Spectroscopic Survey"},
      {acronyme: "BPZ", words: "Bayesian Photo-Z (photometric redshift measurement method)"},
      {acronyme: "BRDF", words: "Bi-directional Reflectance Distribution Function"},
      {acronyme: "BSDF", words: "Bi-directional Scattering Distribution Function"},
      {acronyme: "BSP", words: "Board Support Package"},
      {acronyme: "BSS", words: "Bottom Support Structure (NI-DS)"},
      {acronyme: "BSW", words: "Boot SoftWare"},
      {acronyme: "BTDF", words: "Bi-directional Transmittance Distribution Function"},
      {acronyme: "CAAUL", words: "Centro de Astronomia e Astrophysica da Universidade de Lisboa (Lisbon, Portugal)"},
      {acronyme: "CaC", words: "Cost at Completion"},
      {acronyme: "CAD", words: "Computer Aided Design"},
      {acronyme: "CADC", words: "Canadian Astronomy Data Center (Victoria, Canada)"},
      {acronyme: "CaLA", words: "Camera Lens Assembly (NISP)"},
      {acronyme: "CalCD-A", words: "Calibration Concept Document Part A"},
      {acronyme: "CalCD-B", words: "Calibration Concept Document Part B"},
      {acronyme: "CalWG", words: "(Euclid) Calibration Working Group"},
      {acronyme: "CAUP", words: "Centro de Astrofisica da Universidade do Porto (Porto, Portugal)"},
      {acronyme: "CBE", words: "Current Best Estimate"},
      {acronyme: "CBS", words: "Cost Breakdown Structure"},
      {acronyme: "CCB", words: "Change Control Board / Configuration Control Board"},
      {acronyme: "CCD", words: "Charge Coupled Device"},
      {acronyme: "CCDWG", words: "(Euclid) CCD Working Group"},
      {acronyme: "CCIN2P3", words: "Centre de Calcul de l’IN2P3 (in Lyon, France)"},
      {acronyme: "CCN", words: "Contract Change Note"},
      {acronyme: "CCS", words: "Central Checkout System"},
      {acronyme: "CCSDS", words: "Consultative Committee for Space Data System"},
      {acronyme: "CDE", words: "Coupled Dark Energy"},
      {acronyme: "CDF", words: "Concurrent Design Facility"},
      {acronyme: "CDM", words: "Cold Dark Matter"},
      {acronyme: "CDMS", words: "Command and Data Management System / Cryogenic Dark Matter Search"},
      {acronyme: "CDMU", words: "Command and Data Management Unit"},
      {acronyme: "CDPU", words: "Control and Data Processing Unit (VIS)"},
      {acronyme: "CDR", words: "Critical Design Review"},
      {acronyme: "CDS", words: "Centre de Données astronomiques de Strasbourg (Strasbourg, France)"},
      {acronyme: "CE", words: "Conducted Emission"},
      {acronyme: "CEA", words: "Commissariat à l'Energie Atomique"},
      {acronyme: "CEFCA", words: "Centro de Estudios de Fisica del Cosmos de Aragon (Teruel, Spain)"},
      {acronyme: "CERN", words: "Centre Européen pour la Recherche Nucléaire - European Organisation for Nuclear Research"},
      {acronyme: "CFE", words: "Customer Furnished Equipment"},
      {acronyme: "CFHT", words: "Canada-France-Hawaii Telescope (Mauna Kea, Hawaii, Big Island) / Canada-France-Hawaii Telescope Corporation (Kamuela, Hawaii)"},
      {acronyme: "CFHTLenS", words: "Canada-France-Hawaii Telescope Lensing Survey"},
      {acronyme: "CFHTLS", words: "Canada-France-Hawaii Telescope Legacy Survey"},
      {acronyme: "CFI", words: "Customer Furnished Items"},
      {acronyme: "CFIS", words: "Canada-France Imaging Survey"},
      {acronyme: "CFRP", words: "Carbon Fiber Reinforced Plastic"},
      {acronyme: "CGS", words: "Compagnia General per lo Spazio (Italian industry)"},
      {acronyme: "CI", words: "Configuration Item"},
      {acronyme: "CIB", words: "Cosmic Infrared Background"},
      {acronyme: "CIDL", words: "Configuration Item Data Lists"},
      {acronyme: "CIL", words: "Configuration Item List"},
      {acronyme: "CITA", words: "Canadian Institute for Theoretical Astrophysics (Toronto, Canada)"},
      {acronyme: "CL", words: "CLusters of galaxies / Confidence Level / Corrector Lens"},
      {acronyme: "CLA", words: "Coupled Load Analysis"},
      {acronyme: "CLASH", words: "Cluster Lensing And Supernova survey with Hubble"},
      {acronyme: "CM", words: "Configuration Management / Common Mode / Cryo Mechanism"},
      {acronyme: "CMB", words: "Cosmic Microwave Background"},
      {acronyme: "CMD", words: "Command"},
      {acronyme: "CMOS", words: "Complementary Metal Oxide Silicon"},
      {acronyme: "CMP", words: "Configuration Management Plan"},
      {acronyme: "CMRR", words: "Common Mode Rejection Ratio"},
      {acronyme: "CMU", words: "Compensating Mechanism Unit"},
      {acronyme: "CNES", words: "Centre National d’Etudes Spatiales (France)"},
      {acronyme: "CNRC", words: "Conseil National de Recherches Canada (Canada)"},
      {acronyme: "CNRS", words: "Centre National de la Recherche Scientifique (France)"},
      {acronyme: "COG", words: "Center Of Gravity"},
      {acronyme: "CoLA", words: "Corrector Lens Assembly (NISP)"},
      {acronyme: "COM", words: "COMmunication (EC communication group)"},
      {acronyme: "COMBO-17", words: "Classifying Objects by Medium Band Observations (17 filters)"},
      {acronyme: "COSEBI", words: "Complete Orthogonal Sets of E-B-mode Integrals"},
      {acronyme: "COSMOS", words: "COSMOlogical evolution Survey"},
      {acronyme: "COSPAR", words: "Committee On SPAce Research"},
      {acronyme: "COTS", words: "Commercial Off-The-Shelf"},
      {acronyme: "CPPM", words: "Centre de Physique des Particules de Marseille (Marseille, France)"},
      {acronyme: "CPU", words: "Central Processing Unit"},
      {acronyme: "CPV", words: "Commissioning and Performance Verification"},
      {acronyme: "CR", words: "Change Request / Cosmic Ray"},
      {acronyme: "CRB", words: "Change Review Board"},
      {acronyme: "CRC", words: "Cyclic Redundancy Check"},
      {acronyme: "CS", words: "Conducted Susceptibility"},
      {acronyme: "CSA", words: "Canadian Space Agency (Canada)"},
      {acronyme: "CSIC", words: "CSIC"},
      {acronyme: "CSL", words: "Centre Spatial de Liège (Belgium)"},
      {acronyme: "CSRD", words: "Cosmological Simulations Requirements Document"},
      {acronyme: "CSS", words: "Cold Support Structure (of NI-DS, NISP)"},
      {acronyme: "CTE", words: "Charge Transfer Efficiency / Coefficient of Thermal Expansion"},
      {acronyme: "CTI", words: "Charge Transfer Inefficiency"},
      {acronyme: "CU", words: "Calibration Unit"},
      {acronyme: "CUS", words: "Common Uplink System"},
      {acronyme: "CV", words: "Cosmic Vision (ESA programme)"},
      {acronyme: "CVS", words: "Concurrent Version System"},
      {acronyme: "DAC", words: "Digital to Analog Converter"},
      {acronyme: "DARK", words: "DARK Cosmology Centre (Copenhagen, Denmark)"},
      {acronyme: "DAS", words: "Data Acquisition System"},
      {acronyme: "DB", words: "Data Base"},
      {acronyme: "DC", words: "Direct Current"},
      {acronyme: "DCCM", words: "Document Configuration and Change Management"},
      {acronyme: "DCR", words: "Document Change Request"},
      {acronyme: "DCU", words: "Detector Control Unit"},
      {acronyme: "DDD", words: "Detailed Design Document"},
      {acronyme: "DDL", words: "Deliverable Document List (Document Delivery List)"},
      {acronyme: "DDS", words: "Data Distribution System / Digital Data Storage"},
      {acronyme: "DDV", words: "Design, Development and Verification"},
      {acronyme: "DE", words: "Dark Energy"},
      {acronyme: "DEC", words: "DEClination"},
      {acronyme: "DeM", words: "Demonstration Model"},
      {acronyme: "DES", words: "Dark Energy Survey"},
      {acronyme: "DESC", words: "Dark Energy Science Collaboration"},
      {acronyme: "DESI", words: "Dark Energy Spectroscopic Instrument"},
      {acronyme: "DETF", words: "NASA Dark Energy Task Force"},
      {acronyme: "DEUS", words: "Dark Energu Universe Simulation"},
      {acronyme: "DGP", words: "Dvali, Gabadadze, Porrati model"},
      {acronyme: "DHS", words: "Data Handling System"},
      {acronyme: "DIT", words: "Detector Integration Time"},
      {acronyme: "DJF", words: "Design Justification File"},
      {acronyme: "DLL", words: "Design Limit Loads"},
      {acronyme: "DLR", words: "Deutsches Zentrum für Luft- und Raumfahrt (Germany)"},
      {acronyme: "DM", words: "Dark Matter / Data Model / Development Model / Differential Mode"},
      {acronyme: "DMGSER", words: "Development Model and Ground Support Equipment Requirements"},
      {acronyme: "DMS", words: "Data Management System"},
      {acronyme: "DMSF", words: "Document Management File"},
      {acronyme: "DOE", words: "Department of Energy (USA)"},
      {acronyme: "DoF", words: "Degree of Freedom"},
      {acronyme: "DP", words: "Data Processing / Detector Plane"},
      {acronyme: "DPRD", words: "Data Processing Requirements Document (SGS)"},
      {acronyme: "DPRR", words: "Data Processing Readiness Review (SGS)"},
      {acronyme: "DPU", words: "Data Processing Unit"},
      {acronyme: "DQ", words: "Data Quality"},
      {acronyme: "DQE", words: "Detected Quantum Efficiency"},
      {acronyme: "DQM", words: "Data Quality Mining"},
      {acronyme: "DQR", words: "Daily Quality Report"},
      {acronyme: "DR", words: "Data Release / Design Review"},
      {acronyme: "DRB", words: "Delivery Review Board"},
      {acronyme: "DRD", words: "Document Requirements Descriptions / Document Review Description"},
      {acronyme: "DRL", words: "Document Requirements List"},
      {acronyme: "DS", words: "Deep Survey / Detection System"},
      {acronyme: "DSU", words: "Debug Support Unit"},
      {acronyme: "DTCP", words: "Daily Telemetry Communications Period"},
      {acronyme: "DTA", words: "Damage Threat Assessment"},
      {acronyme: "DTU", words: "Denmark Tekniske Universitet (Lyngby, Denmark)"},
      {acronyme: "DUNE", words: "Dark UNiverse Explorer"},
      {acronyme: "DVP", words: "Development Plan [added]"},
      {acronyme: "DWG", words: "Detector Working Group"},
      {acronyme: "E2E", words: "End-to-End"},
      {acronyme: "EAC", words: "Estimate At Completion"},
      {acronyme: "EACL", words: "Euclid Advisory and Coordination Support Lead"},
      {acronyme: "EACS", words: "Euclid Archive Core System"},
      {acronyme: "EADP", words: "Euclid Archive Development Plan (SGS)"},
      {acronyme: "EAITM", words: "Electrical AIT Manager"},
      {acronyme: "EAITO", words: "Electrical AIT Operator"},
      {acronyme: "EAS", words: "Euclid Archive System"},
      {acronyme: "EAUG", words: "Euclid Archive User Group (SGS)"},
      {acronyme: "EAZY", words: "Easy and Accurate Z from Yale (photometric redshift measurement)"},
      {acronyme: "EC", words: "Euclid Consortium (=EMC)"},
      {acronyme: "ECA", words: "Euclid Contributing Agency"},
      {acronyme: "ECB", words: "Euclid Consortium Board"},
      {acronyme: "ECC", words: "Euclid Consortium Communication / Error Correcting Code"},
      {acronyme: "ECCG", words: "Euclid Consortium Coordination Group"},
      {acronyme: "ECDC", words: "Euclid Consortium Diversity Committee"},
      {acronyme: "ECEB", words: "Euclid Consortium Editorial Board"},
      {acronyme: "ECL", words: "Euclid Consortium Lead"},
      {acronyme: "ECMC", words: "Euclid Consortium Membership Committee"},
      {acronyme: "ECP", words: "Engineering Change Proposal"},
      {acronyme: "ECPG", words: "Euclid Consortium Publication Group"},
      {acronyme: "ECPP", words: "Euclid Consortium Publication Policy"},
      {acronyme: "ECR", words: "Engineering Change Request"},
      {acronyme: "ECSGS", words: "Euclid Consortium Science Ground Segment (SGS)"},
      {acronyme: "EC-SGS", words: "Euclid Consortium Science Ground Segment (SGS)"},
      {acronyme: "ECSS", words: "European Cooperation for Space Standardization"},
      {acronyme: "ECSURV", words: "Euclid Consortium SURVey group"},
      {acronyme: "EDAC", words: "Error Detection and Correction"},
      {acronyme: "EDF", words: "Euclid Deep Field"},
      {acronyme: "EDFN", words: "Euclid Deep Field North"},
      {acronyme: "EDFS", words: "Euclid Deep Field South"},
      {acronyme: "EGI", words: "European Grid Initiative"},
      {acronyme: "EGSE", words: "Electrical Ground Support Equipment"},
      {acronyme: "EE", words: "Encircled Energy / End-to-End tests (=E2E)"},
      {acronyme: "EEE", words: "Electrical, Electronic, and Electromechanical"},
      {acronyme: "E-ELT", words: "European Extremely Large Telescope (ESO, Cerro Armazones, Chili)"},
      {acronyme: "EEPROM", words: "Electrically Erasable Programmable Read-Only Memory"},
      {acronyme: "EFE", words: "ESA Furnished Equipment"},
      {acronyme: "EGSE", words: "Electrical Ground Support Equipment"},
      {acronyme: "EIC", words: "Euclid Imaging Channels"},
      {acronyme: "EID-A", words: "Experiment Interface Document Part A"},
      {acronyme: "EID-B", words: "Experiment Interface Document Part B"},
      {acronyme: "EIDP", words: "End-Item Data Package"},
      {acronyme: "EIQT", words: "Euclid Image Quality Tool"},
      {acronyme: "EIR", words: "Euclid Instrument Requirement"},
      {acronyme: "ELA", words: "Euclid Legacy Archive"},
      {acronyme: "ELG", words: "Early Type Galaxy / Emission Line Galaxy"},
      {acronyme: "E-mode", words: "Pure gravitational lensing signal in gravitational shear analysis - Divergence term 'E' from analogy with Electromagnetic signal"},
      {acronyme: "EM", words: "Electrical Model / Engineering Model"},
      {acronyme: "EMA", words: "Euclid Mission Archive (SGS)"},
      {acronyme: "EMC", words: "ElectroMagnetic Compatibility / Euclid Mission Consortium (=EC)"},
      {acronyme: "EMI", words: "ElectroMagnetic Interference"},
      {acronyme: "EnEI", words: "non-Euclid Imaging"},
      {acronyme: "EO", words: "Earth Observation"},
      {acronyme: "EOAT", words: "Euclid Optimization Advisory Team"},
      {acronyme: "EOL", words: "End Of Life"},
      {acronyme: "EPA", words: "ESD Protected Area (Electro Static Discharge Protected Area)"},
      {acronyme: "EPER", words: "Extended Pixel Edge Response"},
      {acronyme: "EPFL", words: "Ecole Polytechnique Fédérale de Lausanne (Lausanne, Switzerland)"},
      {acronyme: "E-PLM", words: "Extended PayLoad Model"},
      {acronyme: "EPLM", words: "Euclid PayLoad Module"},
      {acronyme: "EPO", words: "Education and Public Outreach"},
      {acronyme: "EPOS", words: "EPO Scientist"},
      {acronyme: "EQM", words: "Engineering and Qualification Model"},
      {acronyme: "EROS", words: "Expérience pour la Recherche d’Objets Sombres"},
      {acronyme: "eROSITA", words: "Extended Röntgen Survey Imaging Telescope Array"},
      {acronyme: "ERS", words: "Euclid Reference Survey"},
      {acronyme: "ES", words: "Electronic Structure"},
      {acronyme: "ESA", words: "European Space Agency"},
      {acronyme: "ESAC", words: "European Space Astronomy Centre (Madrid, Spain)"},
      {acronyme: "ESD", words: "Electro Static Discharge"},
      {acronyme: "ESO", words: "European Southern Observatory"},
      {acronyme: "ESOC", words: "European Space Operation Centre (Darmstadt, Germany)"},
      {acronyme: "ESSPT", words: "Euclid Sky Survey Planning Tool"},
      {acronyme: "ESST", words: "Euclid Science Study Team"},
      {acronyme: "ESSWG", words: "Euclid Sky Survey Working Group"},
      {acronyme: "EST", words: "Euclid Science Team (ESA)"},
      {acronyme: "ESTEC", words: "ESA’s Space research and TEchnology Center (Noordwijk, The Netherlands)"},
      {acronyme: "ESVM", words: "Euclid SerVice Module"},
      {acronyme: "ETC", words: "Exposure Time Calculator"},
      {acronyme: "ETG", words: "Early Type Galaxy"},
      {acronyme: "ETHZ", words: "Eidgenössische Technische Hochschule Zürich (Zürich, Switzerland)"},
      {acronyme: "EVLA", words: "Expanded Very Large Array"},
      {acronyme: "EWS", words: "Euclid Wide Survey"},
      {acronyme: "EZ", words: "Easy-Z (redshift determination)"},
      {acronyme: "FA", words: "Funding Agency"},
      {acronyme: "FAR", words: "Flight Acceptance Review"},
      {acronyme: "F-CDPU", words: "Focal plane Control and Data Processing Unit"},
      {acronyme: "FCT", words: "Fundação para a Ciência e a Tecnologia (Portugal)"},
      {acronyme: "FDIR", words: "Failure Detection Isolation and Recovery"},
      {acronyme: "FE", words: "Front End"},
      {acronyme: "FEM", words: "Finite Element Model"},
      {acronyme: "FFG", words: "ForschungsFörderungsGesellschaft (Austria)"},
      {acronyme: "FFT", words: "Fast Fourier Transform"},
      {acronyme: "FGS", words: "Fine Guidance Sensor"},
      {acronyme: "FH", words: "Flight Harness"},
      {acronyme: "FIR", words: "Far InfraRed"},
      {acronyme: "FITS", words: "Flexible Image Transport System"},
      {acronyme: "FLRW", words: "Friedmann-Lemaître-Roberston-Walker"},
      {acronyme: "FM", words: "Flight Model / Folding Mirror"},
      {acronyme: "FM1", words: "Folding Mirror 1"},
      {acronyme: "FM2", words: "Folding Mirror 2"},
      {acronyme: "FM3", words: "Folding Mirror 3"},
      {acronyme: "FMEA", words: "Failure Mode Effects Analysis"},
      {acronyme: "FMECA", words: "Failure Mode Effects and Criticality Analysis"},
      {acronyme: "FNRS", words: "Fonds National suisse de la Recherche Scientifique (Switzerland)"},
      {acronyme: "FOG", words: "Finger Of God"},
      {acronyme: "FOM", words: "Figure Of Merit"},
      {acronyme: "FOS", words: "Factor Of Safety"},
      {acronyme: "FOV", words: "Field Of View"},
      {acronyme: "FP", words: "Focal Plane"},
      {acronyme: "FP7", words: "(European) 7 Framework Programme"},
      {acronyme: "FPA", words: "Focal Plane Array / Focal Plane Assembly"},
      {acronyme: "FPE", words: "Focal Plane Electronics"},
      {acronyme: "FPGA", words: "Field Programmable Gate Array"},
      {acronyme: "FPU", words: "Floating Point Unit"},
      {acronyme: "FPS", words: "Focal Plane Structure / Focal Plane Support"},
      {acronyme: "F-PSU", words: "Focal plane Power Supply Unit"},
      {acronyme: "FPT", words: "Full Performance Test"},
      {acronyme: "FRR", words: "Flight Readiness Review"},
      {acronyme: "FRW", words: "Friedmann-Robertson-Walker"},
      {acronyme: "FS", words: "Flight Spare"},
      {acronyme: "FSM", words: "Finite State Machine"},
      {acronyme: "FTA", words: "Fault Tree Analysis"},
      {acronyme: "FTE", words: "Full Time Equivalent"},
      {acronyme: "FW", words: "Flight Wheel"},
      {acronyme: "FWA", words: "Filter Wheel Assembly"},
      {acronyme: "FWHM", words: "Full Width Half Maximum"},
      {acronyme: "GADGET", words: "GAlaxies with Dark matter and Gas intEracT"},
      {acronyme: "GALFIT", words: "GALaxy FITting (two dimensional galaxy image decomposition program)"},
      {acronyme: "G3L", words: "Galaxy-Galaxy-Galaxy Lensing"},
      {acronyme: "GaBoDS", words: "Garching-Bonn Deep Survey"},
      {acronyme: "GAMA", words: "Galaxy And Mass Assembly"},
      {acronyme: "GC", words: "Galaxy Clustering"},
      {acronyme: "GCR", words: "Galactic Cosmic Ray"},
      {acronyme: "GC-SWG", words: "Galaxy Clustering Science Working Group"},
      {acronyme: "GDIR", words: "General Design & Interface Requirements"},
      {acronyme: "GDPRD", words: "Ground Data Processing Requirements Document"},
      {acronyme: "GEMS", words: "Galaxy Evolution from Morphology and SED Survey"},
      {acronyme: "GEPI", words: "Galaxies, Etoiles, Physique et Instrumentation (Paris, France)"},
      {acronyme: "GEV", words: "Galaxy and AGN Evolution"},
      {acronyme: "GFRP", words: "Glass Fiber Reinforced Plastic"},
      {acronyme: "GG", words: "(pure) Galaxy-Galaxy lensing signal / Gravitational-Gravitational ellipticity (shear-shear) correlation"},
      {acronyme: "GGL", words: "Galaxy-Galaxy Lensing"},
      {acronyme: "GI", words: "Gravitational-Intrinsic ellipticity (shape-shear) cross-correlations"},
      {acronyme: "GIM2D", words: "Galaxy Image 2-Dimension (two dimensional decomposition program)"},
      {acronyme: "GMM", words: "Geometrical Mathematical Model"},
      {acronyme: "GND", words: "GrouND"},
      {acronyme: "GOODS", words: "Great Observatory Origins Deep Survey"},
      {acronyme: "Gpc", words: "Gigaparsec"},
      {acronyme: "GPGPU", words: "General Purpose Graphical Processing Units"},
      {acronyme: "GPL", words: "General Public Licence"},
      {acronyme: "GPM", words: "Generic Processing Module"},
      {acronyme: "GR", words: "General Relativity"},
      {acronyme: "GRB", words: "Gamma Ray Burst"},
      {acronyme: "GREAT", words: "GRavitational lEnsing Accuracy Testing"},
      {acronyme: "GSDR", words: "Ground Segment Design Review"},
      {acronyme: "GSE", words: "Ground Support Equipment"},
      {acronyme: "GSFC", words: "Goddard Space Flight Center (Greenbelt, USA)"},
      {acronyme: "GSIR", words: "Ground Segment Implementation Review"},
      {acronyme: "GSRQR", words: "Ground Segment Requirements Review"},
      {acronyme: "GSRR", words: "Ground Segment Readiness Review"},
      {acronyme: "GTC", words: "Gran Telescopio Canarias"},
      {acronyme: "GUI", words: "Graphical User Interface"},
      {acronyme: "GW", words: "Gravitational Wave"},
      {acronyme: "GWA", words: "Grism Wheel Assembly"},
      {acronyme: "H2020", words: "Horizon 2020 (European Commission Framework Programme for Research and Innovation 2014-2020)"},
      {acronyme: "H2RG", words: "HAWAII 2RG - HgCdTe Astronomy Wide Area Infrared Imager 2k2 Resolution, Reference pixels and Guide mode"},
      {acronyme: "HAR", words: "Harness"},
      {acronyme: "H/K", words: "House-Keeping"},
      {acronyme: "HPC", words: "High Performance Computing"},
      {acronyme: "HPCC", words: "High Performance Computing Center"},
      {acronyme: "HDF", words: "Hubble Deep Field"},
      {acronyme: "HDR", words: "Hardware Design Review"},
      {acronyme: "HEALPIX", words: "Hierarchical Equal Area isoLatitude PIXelisation"},
      {acronyme: "HETDEX", words: "Hobby-Eberly Telescope Dark Energy Experiment"},
      {acronyme: "HGA", words: "High Gain Antenna"},
      {acronyme: "HgCdTe", words: "Hg (Mercury) Cadmium Telluride"},
      {acronyme: "HOD", words: "Halo Occupation Distribution"},
      {acronyme: "HSC", words: "HyperSuprime Camera (mounted on prime focus of Subaru telescope)"},
      {acronyme: "HST", words: "Hubble Space Telescope"},
      {acronyme: "HW", words: "HardWare (=H/W)"},
      {acronyme: "IAC", words: "Instituto de Astrofísica de Canarias (Canarias, Spain) / International Astronautical Congress"},
      {acronyme: "IADC", words: "Inter-Agency space Debris Coordination Committee"},
      {acronyme: "IAF", words: "International Astronautical Federation"},
      {acronyme: "IAFR", words: "Instrument Acceptance Flight Review"},
      {acronyme: "IAL", words: "Infrastructure Abstraction Layer"},
      {acronyme: "IAP", words: "Image Analysis Pipeline / Institut d’Astrophysique de Paris (Paris, France)"},
      {acronyme: "IAPS", words: "Istituto di Astrofisica e Planatologia Spaziali (Italy)"},
      {acronyme: "IAS", words: "Institut d’Astrophysique Spatiale (Orsay, France)"},
      {acronyme: "IASF", words: "INAF Istituto di Astrofisica Spaziale e Fisica cosmic (Italy)"},
      {acronyme: "IASF-BO", words: "INAF Istituto di Astrofisica Spaziale e Fisica cosmica - Bologna (Bologna, Italy)"},
      {acronyme: "IASF-MI", words: "INAF Istituto di Astrofisica Spaziale e Fisica cosmica - Milan (Milan, Italy)"},
      {acronyme: "IBDR", words: "Instrument Baseline Design Review"},
      {acronyme: "IAL", words: "Infrastructure Abstraction Layer"},
      {acronyme: "ICA", words: "Independent Component Analysis"},
      {acronyme: "ICD", words: "Interface Control Document"},
      {acronyme: "ICDR", words: "Instrument Critical Design Review"},
      {acronyme: "ICE", words: "Institut de Ciencies de l’Espai (Barcelona, Spain)"},
      {acronyme: "ICG", words: "Institute of Cosmology and Gravitation (Portsmouth, UK)"},
      {acronyme: "ICL", words: "Internal Communication Lead / IntraCluster Light"},
      {acronyme: "ICM", words: "IntraCluster Medium"},
      {acronyme: "ICU", words: "Instrument Control Unit"},
      {acronyme: "ID", words: "Identifier"},
      {acronyme: "IDT", words: "Instrument Development Team"},
      {acronyme: "IEEC", words: "Institut d’Estudis Espacial de Catalunya (Barcelona, Spain)"},
      {acronyme: "I/F", words: "InterFace"},
      {acronyme: "IFA", words: "Institute For Astronomy (Edinburgh, UK)"},
      {acronyme: "IFAE", words: "Institut de Fisica d’Altes Energies (Barcelona, Spain)"},
      {acronyme: "IFAR", words: "Instrument Flight Acceptance Review"},
      {acronyme: "IFSI", words: "Istituto di Fisica della Spazio Interplanetario (Italy)"},
      {acronyme: "IGM", words: "InterGalactic Medium"},
      {acronyme: "II", words: "Intrinsic-Intrinsic ellipticity (shape-shape) correlations"},
      {acronyme: "IICD", words: "Internal Interface Control Document"},
      {acronyme: "IIRD", words: "Internal Interface Requirements Document"},
      {acronyme: "IL", words: "Instrument Lead"},
      {acronyme: "ILS", words: "Independent Legacy Scientist"},
      {acronyme: "IM", words: "Interface Module"},
      {acronyme: "IMF", words: "Initial Mass Function"},
      {acronyme: "IN2P3", words: "Institut National de Physique Nucléaire et de Physique des Particules (CNRS, France)"},
      {acronyme: "INAF", words: "Istituto Nazionale AstroFisica (, Italy, see also INAF Osservatorio Astronomico =AO* listed below)"},
      {acronyme: "INFN", words: "Istituto Nazionale di Fisica Nucleare (Italy)"},
      {acronyme: "ING", words: "Isaac Newton Group (La Palma, Spain)"},
      {acronyme: "INSU", words: "Institut National des Sciences de l’Univers (CNRS, France)"},
      {acronyme: "I/O", words: "Input Output"},
      {acronyme: "IoA", words: "Institute of Astronomy (University of Cambridge, UK)"},
      {acronyme: "IOCR", words: "In Orbit Commissioning Review"},
      {acronyme: "IOL", words: "Instrument Operation Lead"},
      {acronyme: "IOT", words: "Instrument Operation Team"},
      {acronyme: "IP", words: "Image Plane"},
      {acronyme: "IPAC", words: "Infrared Processing and Analysis Center (Pasadena, California)"},
      {acronyme: "IPDR", words: "Instrument Preliminary Design Review"},
      {acronyme: "IPNL", words: "Institut de Physique Nucléaire de Lyon (France)"},
      {acronyme: "IPP", words: "Industrial Procurement Plan"},
      {acronyme: "IPQE", words: "IntraPixel Quantum Efficiency"},
      {acronyme: "IPRR", words: "Instrument Preliminary Readiness Review"},
      {acronyme: "IR", words: "InfraRed"},
      {acronyme: "IRAP", words: "Institut de Recherche en Astrophysique et Planétologie (Toulouse, France)"},
      {acronyme: "IRAS", words: "InfraRed Astronomical Satellite"},
      {acronyme: "IRD", words: "Interface Requirements Document"},
      {acronyme: "IQR", words: "Instrument Qualification Review"},
      {acronyme: "IRFU", words: "Institut de Recherche sur les lois Fondamentales de l’Univers - CEA (Saclay, France)"},
      {acronyme: "IRR", words: "Instrument Requirement Review"},
      {acronyme: "IS", words: "Instrument Scientist"},
      {acronyme: "ISDC", words: "Integral Science Data Center (Geneva, Switzerland)"},
      {acronyme: "ISM", words: "Inter Stellar Medium / Iso-Static Mount"},
      {acronyme: "ISO", words: "International Organization for Standardization"},
      {acronyme: "ISS", words: "Institute of Space Science (Magurele, Romania)"},
      {acronyme: "ISSR", words: "Instrument System Requirements Review"},
      {acronyme: "IST", words: "Inter-SWG Taskforce"},
      {acronyme: "ISW", words: "Integrated Sachs Wolfe effect"},
      {acronyme: "IW", words: "Instrument Workstation"},
      {acronyme: "IT", words: "Information Technology"},
      {acronyme: "ITA", words: "Institute of Theoretical Astrophysics (University of Oslo, Norway)"},
      {acronyme: "ITAR", words: "International Traffic in Arms Regulations"},
      {acronyme: "IT-Ind", words: "Italian Industry"},
      {acronyme: "ITN", words: "(Marie Curie) Internal Training Network"},
      {acronyme: "ITT", words: "Invitation To Tender"},
      {acronyme: "IWS", words: "Instrument Work Station"},
      {acronyme: "JAXA", words: "Japan Aerospace Exploration Agency (Japan)"},
      {acronyme: "JDEM", words: "Joint Dark Energy Mission"},
      {acronyme: "JHU", words: "John Hopkins University (Baltimore, Maryland)"},
      {acronyme: "JMU", words: "John Moores University (Liverpool, UK)"},
      {acronyme: "J-PAS", words: "Javalambre Physics of the Accelerating Universe"},
      {acronyme: "JPIP", words: "Joint Project Implementation Plan"},
      {acronyme: "JPL", words: "Jet Propulsion Laboratory (Pasadena, California)"},
      {acronyme: "JWST", words: "James Webb Space Telescope"},
      {acronyme: "KiDS", words: "Kilo Degree Survey"},
      {acronyme: "KIP", words: "Key Inspection Point"},
      {acronyme: "KO", words: "Kick Off"},
      {acronyme: "KOM", words: "Kick Off Meeting"},
      {acronyme: "KSB", words: "Kaiser Squires and Broadhurst (shape measurement method)"},
      {acronyme: "L1", words: "Level 1 Euclid data"},
      {acronyme: "L2", words: "Level 2 Euclid data / Second Lagrange point"},
      {acronyme: "L3", words: "Level 3 Euclid data"},
      {acronyme: "LAM", words: "Laboratoire d’Astrophysique de Marseille (Marseille, France)"},
      {acronyme: "LBG", words: "Lyman Break Galaxies"},
      {acronyme: "LBL", words: "Lawrence Berkeley national Laboratory (Berkeley, California)"},
      {acronyme: "LBT", words: "Large Binocular Telescope"},
      {acronyme: "LC", words: "Inductor-Capacitor circuit"},
      {acronyme: "LCDM", words: "Lambda Cold Dark Matter"},
      {acronyme: "LCL", words: "Latching Current Limiter"},
      {acronyme: "LDAP", words: "Lightweight Directory Access Protocol"},
      {acronyme: "LDPRD", words: "Legacy Data Processing Requirements Document (SGS)"},
      {acronyme: "LED", words: "Light Emitting Diode"},
      {acronyme: "LENSFIT", words: "LENS FITing (bayesian shape measurement method)"},
      {acronyme: "LEOP", words: "Launch and Early Operations Phase"},
      {acronyme: "Le PHARE", words: "PHotometric Analysis for Redshift Estimate (photometric redshift measurement method)"},
      {acronyme: "LET", words: "Linear Energy Transfer"},
      {acronyme: "LF", words: "Luminosity Function"},
      {acronyme: "LFA", words: "Lead Funding Agency"},
      {acronyme: "LGPL", words: "Lesser General Public Licence"},
      {acronyme: "LHC", words: "Large Hadron Collider (CERN)"},
      {acronyme: "LLD", words: "Launch Lock Device"},
      {acronyme: "LLI", words: "Long-Lead Item"},
      {acronyme: "LLIF", words: "Long-Lead Item List"},
      {acronyme: "LMU", words: "Ludwig Maximilians-Universistät München (München, Germany)"},
      {acronyme: "LoA", words: "Letter of Agreement"},
      {acronyme: "LOFAR", words: "LOw Frequency Array for Radio astronomy"},
      {acronyme: "LoI", words: "Letter of Intent"},
      {acronyme: "LOS", words: "Line Of sight"},
      {acronyme: "LPNHE", words: "Laboratoire de Physique Nucléaire et des Hautes Énergies (Paris, France)"},
      {acronyme: "LPP", words: "Lightcurve Processing Pipeline"},
      {acronyme: "LPSC", words: "Laboratoire de Physique Subatomique et de Cosmologie (Grenoble, France)"},
      {acronyme: "LPT", words: "Limited Performance Test"},
      {acronyme: "LRD", words: "Legacy Requirements Document"},
      {acronyme: "LRG", words: "Luminous Red Galaxy"},
      {acronyme: "LRR", words: "Launcher Readiness Review"},
      {acronyme: "LSB", words: "Least Significative Bit / Low Surface Brightness"},
      {acronyme: "LSF", words: "Least Square Fit"},
      {acronyme: "LSST", words: "Large Synoptic Survey Telescope"},
      {acronyme: "LSSTC", words: "Large Synoptic Survey Telescope Corporation (Tucson, Arizona, USA)"},
      {acronyme: "LTB", words: "Lemaître-Tolman-Bondi"},
      {acronyme: "LTG", words: "Late Type Galaxy"},
      {acronyme: "LVDS", words: "Low-Voltage Differential Signal"},
      {acronyme: "LVPS", words: "Low-Voltage Power Supply"},
      {acronyme: "M1", words: "Primary Mirror"},
      {acronyme: "M2", words: "Secondary Mirror"},
      {acronyme: "M3", words: "Tertiary Mirror"},
      {acronyme: "M2M", words: "M2 Mechanism (subsystem)"},
      {acronyme: "M2MM", words: "M2M Mechanism (mechanism part)"},
      {acronyme: "M&C", words: "Monitoring & Control"},
      {acronyme: "MACC", words: "Multi Accumulation Readout"},
      {acronyme: "MACHO", words: "Massive Compact Halo Object"},
      {acronyme: "MAITM", words: "Mechanical AIT Manager"},
      {acronyme: "MAITO", words: "Mechanical AIT Operator"},
      {acronyme: "MAP", words: "JPL Mission Assurance Plan"},
      {acronyme: "MC", words: "Monte Carlo"},
      {acronyme: "MCDR", words: "Mission Critical Design Review"},
      {acronyme: "MCMC", words: "Markov Chain Monte Carlo"},
      {acronyme: "MCRR", words: "Mission Commissioning Results Review"},
      {acronyme: "MCT", words: "Mercury Cadmium Telluride"},
      {acronyme: "MDB", words: "Mission Data Base [added]"},
      {acronyme: "MDE", words: "M2M Drive Electronics"},
      {acronyme: "MDPA", words: "Multi-DSP/Processor Architecture"},
      {acronyme: "MF", words: "Mass Function"},
      {acronyme: "MFAR", words: "Mission Flight Acceptance Review"},
      {acronyme: "MFLOPS", words: "Million Floating Point Operations Per Second"},
      {acronyme: "MG", words: "Modified Gravity"},
      {acronyme: "MGSE", words: "Mechanical Ground Support Equipment"},
      {acronyme: "MICD", words: "Mechanical Interface Control Document"},
      {acronyme: "MINECO", words: "MINisterio de Economia y COmpetividad (Spain)"},
      {acronyme: "MIPS", words: "Mega Instructions Per Second"},
      {acronyme: "MIR", words: "Mid InfaRed"},
      {acronyme: "MIRD", words: "Mission Implementation Requirements Document"},
      {acronyme: "M/L", words: "Mass-to-Light ratio"},
      {acronyme: "ML", words: "Maturity Level (SGS)"},
      {acronyme: "MLA", words: "Multi Lateral Agreement"},
      {acronyme: "MLI", words: "Multi Layer Insulation"},
      {acronyme: "MMU", words: "Mass-Memory Unit"},
      {acronyme: "MOC", words: "Mission Operations Centre / MOlecular Contamination"},
      {acronyme: "MOCD-A", words: "Mission Operation Concept Document Part A"},
      {acronyme: "MOCD-B", words: "Mission Operation Concept Document Part B"},
      {acronyme: "MOGS", words: "Mission Operations Ground Segment"},
      {acronyme: "MOI", words: "Moment Of Inertia"},
      {acronyme: "MOND", words: "MOdified Newtonian Dynamics"},
      {acronyme: "MOONS", words: "Multi-Object Optical and Near-infrared Spectrograph for VLT (Instrument for VLT, 2018)"},
      {acronyme: "MOS", words: "Margin Of Safety / Multi-Object Spectrograph / Metal-Oxyde Silicon"},
      {acronyme: "MOSFET", words: "Metal-Oxyde Semiconductor Field-Effect Transistor"},
      {acronyme: "MOU", words: "Memorandum Of Understanding"},
      {acronyme: "MP", words: "Management Plan"},
      {acronyme: "Mpc", words: "Megaparsec"},
      {acronyme: "MPDR", words: "Mission Preliminary Design Review"},
      {acronyme: "MPE", words: "Max Planck institut für Extraterrestrische physic (Garching, Germany)"},
      {acronyme: "MPIA", words: "Max Planck Institut für Astronomie (Heidelberg, Germany)"},
      {acronyme: "MPP", words: "Milestone Payment Plan"},
      {acronyme: "MPS", words: "Mission Planning System"},
      {acronyme: "MRB", words: "Material Review Board"},
      {acronyme: "MRD", words: "Mission Requirements Document"},
      {acronyme: "MSE", words: "Mirror Surface Error"},
      {acronyme: "MSRR", words: "Mission System Requirements Review"},
      {acronyme: "MSSL", words: "Mullard Space Science Laboratory (UCL, Dorking, UK)"},
      {acronyme: "MTBF", words: "Mean Time Before Failure"},
      {acronyme: "MTD", words: "Mass and Thermal Dummy"},
      {acronyme: "MTF", words: "Modulation Transfer Function"},
      {acronyme: "MW", words: "Milky Way"},
      {acronyme: "MWA", words: "Murchison Wide field Array"},
      {acronyme: "N/A", words: "Not Applicable"},
      {acronyme: "NAOJ", words: "National Astronomical Observatory of Japan (Japan)"},
      {acronyme: "NASA", words: "National Aeronautics and Space Administration (Washington, DC, USA)"},
      {acronyme: "NBI", words: "Niels Bohr Institute (Copenhagen, Denmark)"},
      {acronyme: "NC", words: "Non Convolutive"},
      {acronyme: "NCR", words: "Non-Conformance Report"},
      {acronyme: "NCRB", words: "Non-Conformance Review Board"},
      {acronyme: "NCTS", words: "Non-Conformance Tracking System"},
      {acronyme: "NDI", words: "Non-Destructive Inspection / Normalised Detection Irradiance"},
      {acronyme: "NDRO", words: "Non Destructive Readout"},
      {acronyme: "NEP", words: "North Ecliptic Pole"},
      {acronyme: "NFW", words: "Navarro Frenk and White"},
      {acronyme: "NGP", words: "North Galactic Pole"},
      {acronyme: "NI-", words: "NISP"},
      {acronyme: "NI-CFC", words: "NISP Cryo Flexi Cable (NISP)"},
      {acronyme: "NI-CMS", words: "NI-CMU Simulator (NISP)"},
      {acronyme: "NI-CMT", words: "NI-CMU Test equipment (NISP)"},
      {acronyme: "NI-CMU", words: "NISP Compensation Mechanism Unit (NISP)"},
      {acronyme: "NI-CSS", words: "NISP Cold Support Structure (NISP)"},
      {acronyme: "NI-CU", words: "NISP Calibration Unit (NISP)"},
      {acronyme: "NI-CUS", words: "NI-CU Simulator (NISP)"},
      {acronyme: "NI-CUT", words: "NI-CU Test equipment (NISP)"},
      {acronyme: "NID", words: "NISP Interface Document (NISP)"},
      {acronyme: "NI-DCU", words: "NISP Detector Control Unit (NISP)"},
      {acronyme: "NI-DDT", words: "NI-DCU Development model and Test equipment (NISP)"},
      {acronyme: "NI-DIS", words: "NI-DCU/DPU Test equipment I/F Simulator (NISP)"},
      {acronyme: "NI-DIW", words: "NI-DCU/DPU Test equipment Instrument Workstation (NISP)"},
      {acronyme: "NI-DPU", words: "NISP Data Processing Unit (NISP)"},
      {acronyme: "NI-DS", words: "NISP Detection System (NISP)"},
      {acronyme: "NI-DST", words: "NI-DS Test equipment (NISP)"},
      {acronyme: "NI-DTE", words: "NI-DCU/DPU Test equipment (NISP)"},
      {acronyme: "NI-DTS", words: "NI-DS Thermal control Simulator (NISP)"},
      {acronyme: "NI-DTW", words: "NI-DCU/DPU Test equipment control Workstation (NISP)"},
      {acronyme: "NI-EWS", words: "NISP EGSE control WorkStation (NISP)"},
      {acronyme: "NI-FH", words: "NISP Flight Harness (NISP)"},
      {acronyme: "NI-FPA", words: "NISP Focal plane Assembly (NISP)"},
      {acronyme: "NI-FPS", words: "NI-FPA Simulator (NISP)"},
      {acronyme: "NI-FTT", words: "NI-FPA Thermal control Test equipment (NISP)"},
      {acronyme: "NI-FWA", words: "NISP Filter Wheel Assembly (NISP)"},
      {acronyme: "NI-FWA-CR", words: "NISP Filter Wheel Assemby Cryo Mechanism (NISP)"},
      {acronyme: "NI-FWS", words: "NI-FWA Simulator (NISP)"},
      {acronyme: "NI-FWT", words: "NI-FWA Test equipment (NISP)"},
      {acronyme: "NI-GWA", words: "NISP Grism Wheel Assembly (NISP)"},
      {acronyme: "NI-GWA-CR", words: "NISP Grism Wheel Assembly Cryo Mechanism (NISP)"},
      {acronyme: "NI-GWS", words: "NI-FWA Simulator (NISP)"},
      {acronyme: "NI-GWT", words: "NI-GWA Test equipment (NISP)"},
      {acronyme: "NI-HSS", words: "NISP HarneSS (NISP)"},
      {acronyme: "NI-HSS-IU", words: "NISP Inter Unit Harness (NISP)"},
      {acronyme: "NI-HSS-TH", words: "NISP Thermal Harness (NISP)"},
      {acronyme: "NI-ICU", words: "NISP Instrument Control Unit (NISP)"},
      {acronyme: "NI-IDS", words: "NI-DPU/DCU Interface Simulator (NISP)"},
      {acronyme: "NI-ISS", words: "NI-ICU S/C I/F Simulator (NISP)"},
      {acronyme: "NI-OA", words: "NISP Optics Assembly (NISP)"},
      {acronyme: "NI-OMA", words: "NISP Opto-Mechanical Assembly (NISP)"},
      {acronyme: "NI-OMADA", words: "NI-OMA and Detector Assembly (NISP)"},
      {acronyme: "NI-OTS", words: "NI-OMA Thermal control Simulator (NISP)"},
      {acronyme: "NIP", words: "Near Infrared Photometer (NISP)"},
      {acronyme: "NIR", words: "Near InfraRed"},
      {acronyme: "NIRDWG", words: "(Euclid) Near Infrared Detector Working Group"},
      {acronyme: "NIS", words: "Near Infrared Spectrograph (NISP)"},
      {acronyme: "NI-SA", words: "NISP Structure Assembly"},
      {acronyme: "NI-SCA", words: "NISP Sensor Chip Assembly (NISP)"},
      {acronyme: "NI-SCE", words: "NISP Sensor Chip Electronics (NISP)"},
      {acronyme: "NI-SCS", words: "NISP Sensor Chip System (NISP)"},
      {acronyme: "NI-SSS", words: "NISP Sidecar Support Structure (NISP) / NI-DS Sidecar Support Structure (NISP)"},
      {acronyme: "NISP", words: "Near Infrared Spectrometer and Photometer (NISP)"},
      {acronyme: "NI-TC", words: "NISP Thermal Control (NISP)"},
      {acronyme: "NI-ITE", words: "NI-ICU Test equipment (NISP)"},
      {acronyme: "NI-ITW", words: "NI-ICU Test equipment Workstation (NISP)"},
      {acronyme: "NI-IWS", words: "NISP Instrument Workstation (NISP)"},
      {acronyme: "NI-OMS", words: "NI-OMA Simulator (NISP)"},
      {acronyme: "NI-OTS", words: "NI-OMA Thermal control Simulator (NISP)"},
      {acronyme: "NI-SIS", words: "NISP S/C I/F Simulator (NISP)"},
      {acronyme: "NI-SST", words: "NI-SCS Test equipment (NISP)"},
      {acronyme: "NI-WE", words: "NISP Warm Electronics (NISP)"},
      {acronyme: "NI-WIS", words: "NI-WE Test equipment S/C I/F Simulator (NISP)"},
      {acronyme: "NI-WIW", words: "NI-WE test equipment Instrument Workstation (NISP)"},
      {acronyme: "NI-WTE", words: "NI-WE Test Equipment (NISP)"},
      {acronyme: "NI-WTW", words: "NI-WE Test equipment control Workstation (NISP)"},
      {acronyme: "NL", words: "Non-Linear"},
      {acronyme: "NOAO", words: "National Optical Astronomy Observation (Tucson, Arizona, USA)"},
      {acronyme: "NOVA", words: "Nederlandse Onderzoeschool Voor Astronomie (The Netherlands)"},
      {acronyme: "NPM", words: "National Project Manager"},
      {acronyme: "NRA", words: "NASA Research Announcement"},
      {acronyme: "NRB", words: "Non-conformance Review Board"},
      {acronyme: "NRC", words: "National Research Council (Canada)"},
      {acronyme: "NSC", words: "Norwegian Space Center (Norway)"},
      {acronyme: "NSF", words: "National Science Foundation (USA)"},
      {acronyme: "NSI", words: "National Space Institute (Denmark)"},
      {acronyme: "NSSDC", words: "National Space Science Data Center (NASA)"},
      {acronyme: "NOW", words: "de Nederlandse organisatie voor Wetenschappeliijk Onderzoek (The Netherlands)"},
      {acronyme: "OABr", words: "INAF Osservatorio Astronomico di Brera (Milan, Italy)"},
      {acronyme: "OAITM", words: "Optical AIT Manager"},
      {acronyme: "OAITO", words: "Optical AIT Operator"},
      {acronyme: "OAJ", words: "Observatorio Astrofisico de Javalambre (Spain)"},
      {acronyme: "OAPd", words: "INAF Osservatorio Astronomico di Padova (Padova, Italy)"},
      {acronyme: "OAR", words: "INAF Osservatorio Astronomico di Roma (Rome, Italy) / Off Axis Rejection"},
      {acronyme: "OATo", words: "INAF Osservatorio Astronomico di Torino (Torino, Italy)"},
      {acronyme: "OATs", words: "INAF Osservatorio Astronomico di Trieste (Trieste, Italy)"},
      {acronyme: "OB", words: "Optical Bench"},
      {acronyme: "OBSW", words: "On Board SoftWare"},
      {acronyme: "OCA", words: "Observatoire de la Côte d’Azur (Nice, France)"},
      {acronyme: "OCD", words: "Operation Concept Document"},
      {acronyme: "OGS", words: "Operations Ground Segment"},
      {acronyme: "OGSE", words: "Optical Ground Support Equipment"},
      {acronyme: "OM", words: "Operation and Maintenance / Operation Model (pipelines)"},
      {acronyme: "ORR", words: "Operations Readiness Review"},
      {acronyme: "OSEWG", words: "Operations and System Engineering Working Group"},
      {acronyme: "OSTM", words: "Optical and Structural and Thermal Model"},
      {acronyme: "OT", words: "Operational Temperature"},
      {acronyme: "OTE", words: "Optical Telescope Element"},
      {acronyme: "OTS", words: "Off-The-Shelf"},
      {acronyme: "OU", words: "Organisation Unit (SGS)"},
      {acronyme: "OU-EXT", words: "Organisation Unit EXTernal data (SGS)"},
      {acronyme: "OU-LE3", words: "Organisation Unit LEvel3 data (SGS)"},
      {acronyme: "OU-MER", words: "Organisation Unit MERged data (SGS)"},
      {acronyme: "OU-NIR", words: "Organisation Unit Near InfraRed imaging data (SGS)"},
      {acronyme: "OU-PHZ", words: "Organisation Unit PHoto-Z data (SGS)"},
      {acronyme: "OU-SHE", words: "Organisation Unit SHEar data (SGS)"},
      {acronyme: "OU-SIM", words: "Organisation Unit SIMulation data (SGS)"},
      {acronyme: "OU-SIR", words: "Organisation Unit SPEctral near InfraRed imaging data (SGS)"},
      {acronyme: "OU-SPE", words: "Organisation Unit SPEctral extraction and redshift data (SGS)"},
      {acronyme: "OU-VIS", words: "Organisation Unit VISible imaging data (SGS)"},
      {acronyme: "PA", words: "Product Assurance"},
      {acronyme: "PAC", words: "PArticulate Contamination"},
      {acronyme: "PAD", words: "Part Approval Document"},
      {acronyme: "PAH", words: "Poly-Aromatic Hydrocarbons"},
      {acronyme: "PanSTARRS", words: "Panoramic Survey Telescope Rapid response System"},
      {acronyme: "PAP", words: "Product Assurance Plan"},
      {acronyme: "PA/QA", words: "Product Assurance / Quality Assurance"},
      {acronyme: "PARD", words: "Product Assurance Requirement Document"},
      {acronyme: "PAU", words: "Physics of the Accelerating Universe"},
      {acronyme: "PCA", words: "Principal Component Analysis"},
      {acronyme: "PCB", words: "Printed Circuit Board"},
      {acronyme: "PCDU", words: "Power Conditioning and Distribution Unit"},
      {acronyme: "PCE", words: "Photon to electron Conversion Efficiency"},
      {acronyme: "PDCU", words: "Power Distribution Control Unit"},
      {acronyme: "PDD", words: "Parameter Definition Document / Payload Definition Document / Product Definition Document"},
      {acronyme: "PDF", words: "Probability Density Function / Probability Distribution Function"},
      {acronyme: "PDHU", words: "Processing Data Handling Unit"},
      {acronyme: "PDR", words: "Preliminary Design Review"},
      {acronyme: "PEM", words: "Proximity Electronic Module"},
      {acronyme: "PERD", words: "Payload Element Requirements Document"},
      {acronyme: "PI", words: "Principal Investigator"},
      {acronyme: "PIC", words: "Port d’Informacio Cientifica (Barcelona, Spain)"},
      {acronyme: "PID", words: "Proportional Integral Derivative"},
      {acronyme: "PF", words: "Processing Function (SGS)"},
      {acronyme: "PFCI", words: "Potential Failure Critical Items"},
      {acronyme: "PFE", words: "Prime Furnished Equipment"},
      {acronyme: "PFM", words: "Proto-Flight Model"},
      {acronyme: "PFS", words: "Prime Focus Spectrograph"},
      {acronyme: "PHAT", words: "PHoto-z Accuracy Testing"},
      {acronyme: "PHOTO-z", words: "PHOTOmetric redshift"},
      {acronyme: "P/L", words: "PayLoad"},
      {acronyme: "PLM", words: "PayLoad Module"},
      {acronyme: "PLM-RD", words: "PayLoad Module Requirements Document"},
      {acronyme: "PM", words: "Progress Meeting / Project Manager"},
      {acronyme: "PMCU", words: "Parameters and Mechanism Control Unit (NISP) / Power and Mechanisms Control Unit (VIS)"},
      {acronyme: "PMP", words: "Project Management Plan"},
      {acronyme: "PMRD", words: "Project Management Requirements Document"},
      {acronyme: "PN", words: "Planetary Nebula"},
      {acronyme: "PO", words: "Project Office"},
      {acronyme: "PRACE", words: "PartneRship for Advanced Computing in Europe"},
      {acronyme: "PRNU", words: "Photo Response Non-Uniformity / Pixel Response Non-Uniformity"},
      {acronyme: "PRR", words: "Preliminary Requirements Review"},
      {acronyme: "PRODEX", words: "ESA Programme de Développement d’EXpériences scientifiques"},
      {acronyme: "PROM", words: "Programmable Read Only Memory"},
      {acronyme: "PRTECH", words: "Prototech (Bergen)"},
      {acronyme: "PS", words: "Project Scientist / Pan-STARRS"},
      {acronyme: "PS1", words: "Pan-STARRS-1"},
      {acronyme: "PS2", words: "Pan-STARRS-2"},
      {acronyme: "PSD", words: "Power Spectral Density"},
      {acronyme: "PSF", words: "Point Spread Function"},
      {acronyme: "PSR", words: "Pre-Ship Review"},
      {acronyme: "PSU", words: "Power Supply Unit (ROE VIS) / Power Supply Unit (VIS)"},
      {acronyme: "PWM", words: "Pulse Width Modulation"},
      {acronyme: "PT", words: "Product Tree"},
      {acronyme: "PTR", words: "Post Test Review"},
      {acronyme: "PV", words: "Performance Verification"},
      {acronyme: "QA", words: "Quality Assurance"},
      {acronyme: "QAITM", words: "Quality AIT Manager"},
      {acronyme: "QAITO", words: "Quality AIT Operator"},
      {acronyme: "QC", words: "Quality Control"},
      {acronyme: "QE", words: "Quantum Efficiency"},
      {acronyme: "QLA", words: "Quick Look Analysis (SGS)"},
      {acronyme: "QM", words: "Qualification Model"},
      {acronyme: "QR", words: "Qualification Review"},
      {acronyme: "QSO", words: "Quasi-Stellar Object (quasar)"},
      {acronyme: "RA", words: "Right Ascension"},
      {acronyme: "RAM", words: "Random Access Memory"},
      {acronyme: "RAS", words: "Royal Astronomical Society (London, UK)"},
      {acronyme: "RB", words: "Requirement Baseline"},
      {acronyme: "RCS", words: "Red Cluster Sequence Survey"},
      {acronyme: "RD", words: "Reference Document"},
      {acronyme: "RE", words: "Radiated Emission"},
      {acronyme: "rEE50", words: "50% Encircled Energy radius"},
      {acronyme: "rEE80", words: "80% Encircled Energy radius"},
      {acronyme: "RFA", words: "Request For Approval"},
      {acronyme: "RFD", words: "Request For Deviation"},
      {acronyme: "RFI", words: "Request For Information"},
      {acronyme: "RFQ", words: "Request For Quotation"},
      {acronyme: "RFW", words: "Request For Waiver"},
      {acronyme: "RGMM", words: "Reduced Geometrical Mathematical Model"},
      {acronyme: "RID", words: "Review Item Discrepancy"},
      {acronyme: "RIDS", words: "Review Item Discrepancy System [added]"},
      {acronyme: "RMS", words: "Root Mean Square"},
      {acronyme: "RMW", words: "Read Modify Write"},
      {acronyme: "ROE", words: "Read-Out Electronics (VIS) / Royal Observatory Edinburgh (Edinburgh, UK)"},
      {acronyme: "ROI", words: "Region Of Interest"},
      {acronyme: "ROIC", words: "Readout Integrated Circuit"},
      {acronyme: "ROM", words: "Rough Order of Magnitude"},
      {acronyme: "RON", words: "ReadOut Noise"},
      {acronyme: "ROSA", words: "ROmanian Space Agency (Romania)"},
      {acronyme: "RPE", words: "Relative Pointing Error"},
      {acronyme: "R-PLM", words: "Reduced PayLoad Module"},
      {acronyme: "RPSU", words: "ROE Power Supply Unit (VIS)"},
      {acronyme: "RS", words: "Radiated Susceptibility"},
      {acronyme: "RSD", words: "Redshift Space Distortion / Requirements Specification Document [added]"},
      {acronyme: "RSSD", words: "ESA Research and Space Support Department (ESA, ESTEC, Noordwijk, The Netherlands)"},
      {acronyme: "RSU", words: "Read-out Shutter Unit (VIS)"},
      {acronyme: "RT", words: "Real Time pipeline / Remote Terminal / Room Temperature"},
      {acronyme: "RTA", words: "Real Time Assessment"},
      {acronyme: "RTD", words: "Resistance Temperature Device"},
      {acronyme: "RTMM", words: "Reduced Thermal Mathematical Model"},
      {acronyme: "RuG", words: "Rijkuniversiteit Groningen (Groningen, The Netherlands)"},
      {acronyme: "SAA", words: "Solar Aspect Angle"},
      {acronyme: "SAID", words: "Science Analysis Implementation Document"},
      {acronyme: "Sap", words: "Service d’Astrophysique - CEA/IRFU (Saclay, France)"},
      {acronyme: "SARD", words: "System AIV Requirements Document"},
      {acronyme: "SAT", words: "Science Archive Team"},
      {acronyme: "S/C", words: "SpaceCraft"},
      {acronyme: "SC", words: "Scientific Challenge (SGS)"},
      {acronyme: "SCA", words: "Sensor Chip Assembly (NISP)"},
      {acronyme: "SCE", words: "Sensor Chip Electronic (NISP)"},
      {acronyme: "SCET", words: "SpaceCraft Elapsed Time"},
      {acronyme: "SciRD", words: "Science Requirements Document"},
      {acronyme: "SCM", words: "Software Configuration Management"},
      {acronyme: "SCMP", words: "Software Configuration Management Plan"},
      {acronyme: "SCR", words: "Software Change Request"},
      {acronyme: "SCOE", words: "Specific Check Out Equipment"},
      {acronyme: "SCOS", words: "Satellite Control and Operation System / Space Craft Operating System"},
      {acronyme: "SCS", words: "Sensor Chip System (NISP)"},
      {acronyme: "SDC", words: "Science Data Center (SGS)"},
      {acronyme: "SDC-DEV", words: "SDC-DEVelopment (SGS)"},
      {acronyme: "SDC-PROD", words: "SDC-PRODuction (SGS)"},
      {acronyme: "SDM", words: "SOC Development Manager"},
      {acronyme: "SDR", words: "Software Development Repositories"},
      {acronyme: "SDSS", words: "Sloan Digital Sky Survey"},
      {acronyme: "SED", words: "Single Event Damage / Spectral Energy Distribution"},
      {acronyme: "SEE", words: "Single Event Effect"},
      {acronyme: "SEL", words: "Single Event Latch-up"},
      {acronyme: "SEL-2", words: "Sun-Earth Lagrange point 2 (=L2)"},
      {acronyme: "SEMP", words: "System Engineering Management Plan"},
      {acronyme: "SEP", words: "South Ecliptic Pole / System Engineering Plan"},
      {acronyme: "SER", words: "Secrétaire d’Etat à l’Education et à la Recherche (Switzerland)"},
      {acronyme: "SEU", words: "Single Event Upset"},
      {acronyme: "SFR", words: "Star Formation Rate"},
      {acronyme: "SG", words: "Science Group"},
      {acronyme: "SGP", words: "South Galactic Pole"},
      {acronyme: "SGS", words: "Science Ground Segment"},
      {acronyme: "SGSS", words: "Science Ground Segment Scientist"},
      {acronyme: "SI", words: "International System of Units (Système International)"},
      {acronyme: "SiC", words: "Silicon Carbide"},
      {acronyme: "SIDECAR", words: "System for Image Digitization, Enhancement, Control And Retrieval (NISP)"},
      {acronyme: "SIDM", words: "Self-Interacting Dark Matter"},
      {acronyme: "SIF", words: "Service InterFace"},
      {acronyme: "SIM-SWG", words: "Simulations Science Working Group"},
      {acronyme: "SIP", words: "Science Ground Segment Implementation Plan (SGS)"},
      {acronyme: "SIR", words: "System Integration Review"},
      {acronyme: "SIRD", words: "Science Implementation Requirements Document (SGS)"},
      {acronyme: "SIS", words: "Service d’Ingénierie des Systèmes - CEA/IRFU (Saclay, France)"},
      {acronyme: "SISSA", words: "Scuola Internazionale Superiore di Studi Avanzati (Trieste, Italy)"},
      {acronyme: "SIVVP", words: "Software Integration, Validation and Verification Plan"},
      {acronyme: "SKA", words: "Square Kilometre Array (Manchester, UK)"},
      {acronyme: "SL", words: "Strong Lensing / System Lead"},
      {acronyme: "SLI", words: "Single Layer Insulation"},
      {acronyme: "SME", words: "Surface Mirror Error"},
      {acronyme: "SMM", words: "Structural Mathematical Model"},
      {acronyme: "SMP", words: "Science Management Plan"},
      {acronyme: "SMT", words: "Surface-Mount Technology"},
      {acronyme: "S/N", words: "Signal-to-Noise ratio"},
      {acronyme: "SN", words: "SuperNova"},
      {acronyme: "SNIa", words: "Type Ia SuperNova"},
      {acronyme: "SNLS", words: "SuperNova Legacy Survey"},
      {acronyme: "SNR", words: "Signal to Noise Ratio"},
      {acronyme: "SNT", words: "SuperNova and Transients"},
      {acronyme: "SOC", words: "Science Operation Center (SGS) / Statement Of Compliance"},
      {acronyme: "SOCD", words: "Science Operations Concept Document (SGS)"},
      {acronyme: "SOD", words: "Science Operation Department"},
      {acronyme: "SODD", words: "Science Output Definition Document"},
      {acronyme: "SOVT", words: "Science Operations Verification Tests"},
      {acronyme: "SOW", words: "Statement Of Work"},
      {acronyme: "SPA", words: "Software Product Assurance"},
      {acronyme: "SPACE", words: "Spectroscopic All-Sky Cosmic Explorer"},
      {acronyme: "SPAP", words: "Software Product Assurance Plan"},
      {acronyme: "SPARC", words: "Scalable Processor ARChitecture"},
      {acronyme: "SPBD", words: "System Performance Budget Document"},
      {acronyme: "SPC", words: "Science Programme Committee (ESA)"},
      {acronyme: "SPI", words: "Serial Peripheral Interface"},
      {acronyme: "SPM", words: "Software Product Manager"},
      {acronyme: "SPR", words: "Science Performance Review"},
      {acronyme: "SPSAA", words: "Solar Panel Solar Aspect Angle"},
      {acronyme: "SPT", words: "South Pole Telescope"},
      {acronyme: "SPV", words: "Science Performance Verification"},
      {acronyme: "SPW", words: "SPace Wire"},
      {acronyme: "SQAP", words: "Software Quality Assurance Plan"},
      {acronyme: "SQL", words: "Structured Query Language"},
      {acronyme: "SRAM", words: "Static Random Access Memory"},
      {acronyme: "SRB", words: "Software Review Board"},
      {acronyme: "SRD", words: "Software Requirements Document / System Requirements Document"},
      {acronyme: "SRE", words: "ESA Science and Robotic Exploration"},
      {acronyme: "SRE-O", words: "SRE-Operations department"},
      {acronyme: "SRR", words: "System Requirements Review"},
      {acronyme: "SSA", words: "SunShield Assembly"},
      {acronyme: "SSC", words: "Sensor System Chip / Space Science Center (Denmark)"},
      {acronyme: "SSE", words: "Sun-Spacecraft Earth angle"},
      {acronyme: "SSH", words: "SunSHield"},
      {acronyme: "ST", words: "Science Team / Steering Committee"},
      {acronyme: "STAR", words: "Special Thanks And Recognition"},
      {acronyme: "STEP", words: "Shear Testing Programme"},
      {acronyme: "STFC", words: "Science and Technology Facilities Council (UK)"},
      {acronyme: "STM", words: "Structural & Thermal Model"},
      {acronyme: "STR", words: "Star TRacker"},
      {acronyme: "SU", words: "Shutter Unit"},
      {acronyme: "SUM", words: "Software User Manual [added]"},
      {acronyme: "SUMIRE", words: "Subaru Measurement of Images and Redshifts (Instrument for Subaru telescope)"},
      {acronyme: "SUNGLASS", words: "Simulated Universes for Gravitational Lensing Anaysis and Shear Surveys"},
      {acronyme: "SUR", words: "Science User Requirements"},
      {acronyme: "SVM", words: "SerVice Module"},
      {acronyme: "SVN", words: "SubVersioN"},
      {acronyme: "SVT", words: "System Verification Testing"},
      {acronyme: "SVVP", words: "System Validation and Verification Plan"},
      {acronyme: "STS", words: "Software Test Specifications"},
      {acronyme: "STScI", words: "Space Telescope Science Institute (Baltimore, Maryland, USA)"},
      {acronyme: "S/W", words: "SoftWare"},
      {acronyme: "SWG", words: "Science Working Group"},
      {acronyme: "SWL", words: "Space Wire Link"},
      {acronyme: "SZ", words: "Sunyaev-Zeldovich"},
      {acronyme: "TA", words: "Telescope Assembly"},
      {acronyme: "TAA", words: "Technical Assistance Agreement"},
      {acronyme: "TAITM", words: "Thermal AIT Manager"},
      {acronyme: "TAITO", words: "Thermal AIT Operator"},
      {acronyme: "TAS", words: "Thales Alenia Space"},
      {acronyme: "TAS-I", words: "TAS-Italia"},
      {acronyme: "TB", words: "Thermal Balance"},
      {acronyme: "TBA", words: "To Be Assigned / To Be Appointed"},
      {acronyme: "TBC", words: "To Be Confirmed"},
      {acronyme: "TBD", words: "To Be Defined/Determined"},
      {acronyme: "TBR", words: "To Be Revised"},
      {acronyme: "TBT", words: "Thermal Balance Test"},
      {acronyme: "TBV", words: "To Be Verified"},
      {acronyme: "TBW", words: "To Be Written"},
      {acronyme: "TC", words: "TeleCommand"},
      {acronyme: "TCS", words: "Thermal Control System"},
      {acronyme: "TDA", words: "Technology Development Activity"},
      {acronyme: "TE", words: "Test Equipment"},
      {acronyme: "TEKES", words: "TEknologian ja innovaatioiden KEhittämiskeskuS (Helsinki, Finland)"},
      {acronyme: "TeVeS", words: "Tensor Vector Scalar"},
      {acronyme: "TGSE", words: "Thermal Ground Support Equipment"},
      {acronyme: "TH-SWG", words: "Theory Science Working Group"},
      {acronyme: "TID", words: "Total Ionising Dose"},
      {acronyme: "TIF", words: "Thermal InterFace"},
      {acronyme: "TIM", words: "Technical Information Meeting"},
      {acronyme: "TIS", words: "Teledyne Imaging Systems / Teledyne Imaging Sensors / Total Integrated Scattering"},
      {acronyme: "TK", words: "Technical Key point (SGS)"},
      {acronyme: "TLM", words: "Telemetry"},
      {acronyme: "TM", words: "TeleMetry"},
      {acronyme: "TMA", words: "Three Mirrors Anastigmat"},
      {acronyme: "TMM", words: "Thermal Mathematical Model"},
      {acronyme: "TMT", words: "Thirty Meter Telescope"},
      {acronyme: "TN", words: "Technical Note"},
      {acronyme: "Top", words: "Temperature Operating"},
      {acronyme: "ToR", words: "Terms of Reference"},
      {acronyme: "TR", words: "software TRansfer phase"},
      {acronyme: "TRB", words: "Test Review Board"},
      {acronyme: "TRL", words: "Technology Readiness Level"},
      {acronyme: "TRP", words: "Temperature Reference Point"},
      {acronyme: "TRR", words: "Test Readiness Review"},
      {acronyme: "TT", words: "(Euclid) Tiger Team"},
      {acronyme: "TT&C", words: "Telemetry, Tracking and Command"},
      {acronyme: "TV", words: "Thermal Vacuum"},
      {acronyme: "UAH", words: "University of Alcalá de Henares (Spain)"},
      {acronyme: "UC", words: "University of California (California)"},
      {acronyme: "UCL", words: "University College London (London, UK)"},
      {acronyme: "UDF", words: "Ultra-Deep Field"},
      {acronyme: "UH", words: "University of Helsinki (Helsinki, Finland) / University of Hawaii (Hawaii, USA)"},
      {acronyme: "UIO", words: "Universitetet I Oslo (Oslo, Norway)"},
      {acronyme: "UKIDS", words: "UKIRT Infrared Deep Sky Survey"},
      {acronyme: "UKIDSS-LAS", words: "UKIRT Infrared Deep Sky Survey Large Area Survey"},
      {acronyme: "UKIRT", words: "United Kingdom InfraRed Telescope"},
      {acronyme: "UKSA", words: "United Kingdom Space Agency (UK)"},
      {acronyme: "UMA", words: "Universidad Autonomia de Madrid (Madrid, Spain)"},
      {acronyme: "UML", words: "Unified Modeling Language"},
      {acronyme: "UoG", words: "University of Geneva (Geneva, Switzerland)"},
      {acronyme: "UoT", words: "University of Toronto (Toronto, Canada)"},
      {acronyme: "UPCT", words: "Universidad Politécnica de CarTagena - Technical University of Cartagena (Cartagena, Spain)"},
      {acronyme: "UPenn", words: "University of Pennsylvania (Philadelphia, Pennsylvania)"},
      {acronyme: "UPMC", words: "Université Pierre et Marie Curie (Paris, France)"},
      {acronyme: "URD", words: "User Requirements Document"},
      {acronyme: "URF", words: "Unit Reference Frame"},
      {acronyme: "USM", words: "Universitäts-Sternwarte München (München Germany)"},
      {acronyme: "USNO", words: "US Naval Observatory (Washington, DC, USA)"},
      {acronyme: "USS", words: "Upper Support Structure (NI-DS, NISP)"},
      {acronyme: "UT", words: "Unit Tester"},
      {acronyme: "UTR", words: "Up The Ramp Readout (NISP)"},
      {acronyme: "UUT", words: "Unit Under Test"},
      {acronyme: "UVic", words: "University of Victoria (Victoria, Canada)"},
      {acronyme: "V&V", words: "Validation and Verification"},
      {acronyme: "VCD", words: "Verification Control Document"},
      {acronyme: "VGS", words: "Verification Ground Support"},
      {acronyme: "VI-", words: "VIS"},
      {acronyme: "VI-CDPU", words: "VIS Control and Data Processing Unit (VIS)"},
      {acronyme: "VI-CU", words: "VIS Calibration Unit (VIS)"},
      {acronyme: "VDA", words: "Vapour Deposit Aluminium"},
      {acronyme: "VIDEO", words: "VISTA Deep Extragalactic Observatory survey"},
      {acronyme: "VI-FPA", words: "VIS Focal Plane Assembly (VIS)"},
      {acronyme: "VI-FPA-DP", words: "VIS FPA Detector Panel (VIS)"},
      {acronyme: "VI-FPA-ES", words: "VIS FPA Electronic Structure (VIS)"},
      {acronyme: "VI-HAR", words: "VIS HARness (VIS)"},
      {acronyme: "VI-FH", words: "VIS Flight Harness (VIS)"},
      {acronyme: "VIKING", words: "VISTA Kilo degree INfrared Galaxy survey"},
      {acronyme: "VIMOS", words: "Visible wide field Imager and Multi-Object Spectrograph"},
      {acronyme: "VI-PMCU", words: "VIS Power and Mechanisms Control Unit (VIS)"},
      {acronyme: "VIPERS", words: "VIMOS Public Extragalactic Redshift Survey"},
      {acronyme: "VIPM", words: "VIS Project Manager (VIS)"},
      {acronyme: "VI-RSU", words: "VIS Read-out Shutter Unit (VIS)"},
      {acronyme: "VIS", words: "VISible Instrument"},
      {acronyme: "VISTA", words: "Visible and Infrared Survey Telescope for Astronomy"},
      {acronyme: "VI-SU", words: "VIS Shutter Unit (VIS)"},
      {acronyme: "VLA", words: "Very Large Array"},
      {acronyme: "VLT", words: "ESO Very Large Telescope"},
      {acronyme: "VO", words: "Virtual Observatory"},
      {acronyme: "VObs", words: "Virtual Observatory"},
      {acronyme: "VPD", words: "Validation Plan Document [added]"},
      {acronyme: "VST", words: "VLT Survey Telescope"},
      {acronyme: "VUDS", words: "VIMOS Ultra Deep Survey"},
      {acronyme: "VVDS", words: "VIMOS VLT Deep survey"},
      {acronyme: "WA", words: "Worst Average PSF"},
      {acronyme: "WBS", words: "Work Breakdown Structure"},
      {acronyme: "WCS", words: "World Coordinate System"},
      {acronyme: "WDM", words: "Warm Dark Matter"},
      {acronyme: "WE", words: "Warm Electronics"},
      {acronyme: "WEAVE", words: "WHT Enhanced Area Velocity Explorer"},
      {acronyme: "WFC3", words: "HST Wide Field Camera 3"},
      {acronyme: "WFE", words: "Wave Front Error"},
      {acronyme: "WFIRST", words: "Wide Field InfraRed Telescope"},
      {acronyme: "WFS", words: "Wave Front Sensor"},
      {acronyme: "WG", words: "Working Group"},
      {acronyme: "WHT", words: "William Herschel Telescope"},
      {acronyme: "WIMP", words: "Weakly Interacting Massive Particle"},
      {acronyme: "WISE", words: "Wide field Infrared Survey Explorer"},
      {acronyme: "WL", words: "Weak Lensing"},
      {acronyme: "WL-SWG", words: "Weak Lensing Science Working Group"},
      {acronyme: "WMAP", words: "Wilkinson Microwave-Anisotropy Probe"},
      {acronyme: "WP", words: "Work Package"},
      {acronyme: "WPBD", words: "Work Package Breakdown and Description"},
      {acronyme: "WPD", words: "Work Package Description"},
      {acronyme: "WR", words: "Worst Red PSF"},
      {acronyme: "WS", words: "Wide Survey"},
      {acronyme: "XC", words: "Cross-Correlation"},
      {acronyme: "XML", words: "eXtensible Markup Language"},
      {acronyme: "XMM", words: "X-ray Multi-Mirror Telescope"},
      {acronyme: "XSD", words: "XML Schema Definition"},
      {acronyme: "ZEBRA", words: "Zurich Extragalactic Bayesian Redshift Analyser (photometric redshift measurement method)"},
      {acronyme: "ZODI", words: "ZODIacal / ZODIacal dust unit"}
    ];
  }

  getItems(ev) {
    // Reset ecal back to all of the acronyme
    this.initializeItems();

    // set val to the value of the ev target
    var val = ev.target.value;

    // if the value is an empty string don't filter the acronyme
    if (val && val.trim() != '') {
      this.ecal = this.ecal.filter(item => {
        return (item.acronyme.toLowerCase().indexOf(val.toLowerCase()) > -1);
      })
    }
  }
}
